insert into DETAILED_COST_CLUSTER (ID, NAME, COST_CLUSTER) VALUES(ID_SEQUENCE.NEXTVAL, 'Sparen-1','SPAREN');
insert into COST_RECIPIENT (ID, NAME) VALUES(ID_SEQUENCE.NEXTVAL, 'R1');
insert into COST_ITEM (ID, RECIPIENT_ID, PURPOSE, AMOUNT, OWNER, TYPE, DETAILED_CLUSTER_ID, CREATION_DATE_NEW)
VALUES(ID_SEQUENCE.nextval, (select id from COST_RECIPIENT where name='R1'), 'SomePurpose', -100.1, 'MISCHA',
       'FLEXIBEL', (select id from DETAILED_COST_CLUSTER where NAME='Sparen-1'), TO_TIMESTAMP('2019-11-09', 'YYYY-MM-DD'));

insert into COST_ITEM (ID, RECIPIENT_ID, PURPOSE, AMOUNT, OWNER, TYPE, DETAILED_CLUSTER_ID, CREATION_DATE_NEW)
VALUES(ID_SEQUENCE.nextval, (select id from COST_RECIPIENT where name='R1'), 'SomePurpose', -100.1, 'MISCHA',
       'FLEXIBEL', (select id from DETAILED_COST_CLUSTER where NAME='Sparen-1'), TO_TIMESTAMP('2019-12-09', 'YYYY-MM-DD'));
